### ISSUE TITLE
proposiciones

### ISSUE THREAD

**Issue by elisa1223** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-elisa1223#1]
[elisa_sanchez_coronel_proposiciones.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-elisa1223/files/13193662/elisa_sanchez_coronel_proposiciones.pdf)

**Comment by ghost** [comment]
Portada: 25/25
Procedimiento: 20/25 (No contiene Lista de Figuras)
Figuras: 15/25 (No contiene todas las figuras)
Resultados y conclusiones: 25/25
total: 85/100

Puntaje final: 17/20
Calificado por equipo de: Mayra, Diego, Félix, Daniel.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
